"""create_initial_tables

Revision ID: 294f32308b3b
Revises: 
Create Date: 2026-10-01 22:05:09.929145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294f32308b3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', 'BLOQUEADO', name='estado_usuario'), server_default='ACTIVO', nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('transacciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_txn', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_txn', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_recepcion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Enum('APROBADA', 'SOSPECHOSA', 'RECHAZADA', name='estado_transaccion'), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('metodo_pago', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_txn', name='uq_transacciones_id_txn')
    )
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.create_index('ix_transacciones_estado', ['estado'], unique=False)
        batch_op.create_index('ix_transacciones_fecha_txn', ['fecha_txn'], unique=False)
        batch_op.create_index('ix_transacciones_id_txn', ['id_txn'], unique=False)
        batch_op.create_index('ix_transacciones_usuario_id', ['usuario_id'], unique=False)

    op.create_table('anomalias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaccion_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('POSIBLE_FRAUDE', name='tipo_anomalia'), nullable=False),
    sa.Column('nivel', sa.Enum('BAJO', 'MEDIO', 'ALTO', 'CRITICO', name='nivel_anomalia'), nullable=False),
    sa.Column('cantidad_transacciones', sa.Integer(), nullable=False),
    sa.Column('ventana_segundos', sa.Integer(), nullable=False),
    sa.Column('regla_detectada', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('estado_revision', sa.Enum('NUEVA', 'ABIERTA', 'REVISADA', 'DESCARTADA', name='estado_revision'), server_default='NUEVA', nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['transaccion_id'], ['transacciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomalias')
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.drop_index('ix_transacciones_usuario_id')
        batch_op.drop_index('ix_transacciones_id_txn')
        batch_op.drop_index('ix_transacciones_fecha_txn')
        batch_op.drop_index('ix_transacciones_estado')

    op.drop_table('transacciones')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
